CREATE TABLE employee (
    id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    first_name VARCHAR (30) NOT NULL
    last_name VARCHAR (30) NOT NULL
);

CREATE TABLE department (
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY
ful;l_name VARCHAR(30)
);

-- CREATE TABLE role(
-- id INTEGER AUTO_INCREMENT PRIMARY KEY 
-- title VARCHAR (30) NOT NULL
-- salary DECIMAL 
-- department_id INT 
-- )
